vich_uploader:
    db_driver: orm

    mappings:
        articles:
            uri_prefix: /images/articles
            upload_destination: '%kernel.project_dir%/public/images/articles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        events:
            uri_prefix: /images/events
            upload_destination: '%kernel.project_dir%/public/images/events'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        missions:
            uri_prefix: /images/missions
            upload_destination: '%kernel.project_dir%/public/images/missions'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        videos:
            uri_prefix: /images/videos
            upload_destination: '%kernel.project_dir%/public/images/videos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        header:
            uri_prefix: /images/header
            upload_destination: '%kernel.project_dir%/public/images/header'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

